export type CampaignStatus = "funded" | "high-priority";

export type MarketplaceCampaign = {
  id: string;
  title: string;
  description: string;
  status: CampaignStatus;
  statusLabel: string;
  refId: string;
  payout: string;
  currency: string;
  deadline: string;
  applicantAvatars: number;
  hasApplyNow: boolean;
};

export const marketplaceCampaigns: MarketplaceCampaign[] = [
  {
    id: "nextgen-wallet",
    title: "NextGen Wallet Review",
    description: "Create a 60-second tutorial on setting up a trustline for USDC on Stellar. High engagement required.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "ID: #BA-0922",
    payout: "2,450.00",
    currency: "USDC",
    deadline: "14 Days",
    applicantAvatars: 3,
    hasApplyNow: false,
  },
  {
    id: "lumen-node",
    title: "Lumen Node Operator UGC",
    description: "Explain the benefits of running a validator node on the Stellar network. Target audience: Developers & IT pros.",
    status: "high-priority",
    statusLabel: "HIGH PRIORITY",
    refId: "",
    payout: "15,000",
    currency: "XLM",
    deadline: "5 Days",
    applicantAvatars: 2,
    hasApplyNow: true,
  },
  {
    id: "cross-border",
    title: "Cross-Border Storytelling",
    description: "Document your experience sending money from Lagos to Nairobi using the latest fintech bridge. Authentic, raw footage.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "",
    payout: "850,000",
    currency: "NGN",
    deadline: "21 Days",
    applicantAvatars: 1,
    hasApplyNow: false,
  },
  {
    id: "twitter-alpha",
    title: "Twitter Alpha Thread",
    description: "A 10-post deep dive into Soroban smart contracts for traditional finance audiences. Technical but accessible.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "",
    payout: "1,200.00",
    currency: "USDC",
    deadline: "2 Days",
    applicantAvatars: 1,
    hasApplyNow: false,
  },
  {
    id: "healthy-habits",
    title: "Healthy Habits x Stellar",
    description: "Lifestyle content showing how you use Anchor-powered savings apps to fund your wellness routine.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "",
    payout: "150,000",
    currency: "KES",
    deadline: "10 Days",
    applicantAvatars: 2,
    hasApplyNow: false,
  },
  {
    id: "defi-moms",
    title: "DeFi Explained for Moms",
    description: "Create a relatable video explaining why holding stablecoins is safer than local currency during inflation.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "",
    payout: "3,000.00",
    currency: "USDC",
    deadline: "7 Days",
    applicantAvatars: 1,
    hasApplyNow: false,
  },
  {
    id: "stellar-startup",
    title: "Stellar Startup Spotlight",
    description: "Interview-style reel featuring a founder building on Soroban. Focus on real use cases and traction.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "ID: #BA-1041",
    payout: "4,800.00",
    currency: "USDC",
    deadline: "12 Days",
    applicantAvatars: 2,
    hasApplyNow: false,
  },
  {
    id: "anchor-walkthrough",
    title: "Anchor On-Ramp Walkthrough",
    description: "Screen recording showing a first-time user depositing NGN through a Stellar anchor and receiving USDC.",
    status: "high-priority",
    statusLabel: "HIGH PRIORITY",
    refId: "",
    payout: "920,000",
    currency: "NGN",
    deadline: "4 Days",
    applicantAvatars: 3,
    hasApplyNow: true,
  },
  {
    id: "creator-toolkit",
    title: "Creator Toolkit Unboxing",
    description: "Short-form content reviewing AdsBazaar campaign tools for new creators joining the marketplace.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "",
    payout: "1,800.00",
    currency: "USDC",
    deadline: "9 Days",
    applicantAvatars: 1,
    hasApplyNow: false,
  },
  {
    id: "mobile-money-bridge",
    title: "Mobile Money Bridge Demo",
    description: "Document sending KES via M-Pesa rail and receiving stablecoin payout on Stellar within minutes.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "",
    payout: "220,000",
    currency: "KES",
    deadline: "16 Days",
    applicantAvatars: 2,
    hasApplyNow: false,
  },
  {
    id: "web3-edu-series",
    title: "Web3 Education Mini-Series",
    description: "Three-part carousel explaining escrow, milestones, and creator payouts for non-crypto audiences.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "",
    payout: "6,500.00",
    currency: "USDC",
    deadline: "18 Days",
    applicantAvatars: 4,
    hasApplyNow: false,
  },
  {
    id: "fintech-comparison",
    title: "Fintech Comparison Thread",
    description: "Compare cross-border remittance fees vs Stellar anchor routes with charts and personal commentary.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "",
    payout: "2,100.00",
    currency: "USDC",
    deadline: "6 Days",
    applicantAvatars: 1,
    hasApplyNow: false,
  },
  {
    id: "community-ama",
    title: "Community AMA Highlights",
    description: "Edit the best moments from a live AMA about creator earnings and publish as a recap video.",
    status: "funded",
    statusLabel: "FUNDED",
    refId: "",
    payout: "9,500",
    currency: "XLM",
    deadline: "3 Days",
    applicantAvatars: 2,
    hasApplyNow: true,
  },
];

export const quickTags = ["WEB3 NATIVE", "E-COMMERCE", "TIKTOK TREND", "UGC"];
